;;Author: Tyler Paulsen
(val empty-int (@ '() int))
(val nullI (@ null? int))
(val carI (@ car int))
(val consI (@ cons int))
(val cdrI (@ cdr int))
(val eqI (@ = int))
;;Question 1
(define bool findInList (((list int) lst) (int x))
	(if ( nullI lst)
		#f
		(if (eqI (carI lst) x )
			#t
			(findInList (cdrI lst) x)
		)
	)
)
;;;Question 2
(define int maxValHelper ( ((list int) lst) (int x) )
	(if (nullI lst)
		x
		(if (eqI x 0)
			(maxValHelper lst (carI lst))
			(if (< x (carI lst))
				(maxValHelper (cdrI lst) (carI lst))
				(maxValHelper (cdrI lst) x)
			)
		)
	)
)
(define int maxValue ( ((list int) lst))
	(maxValHelper lst 0 )	
)

;;;Question 3
(define int minValHelper ( ((list int) lst) (int x) )
	(if (nullI lst)
		x
		(if (eqI x 0)
			(minValHelper lst (carI lst))
			(if (> x (carI lst))
				(minValHelper (cdrI lst) (carI lst))
				(minValHelper (cdrI lst) x)
			)
		)
	)
)
(define int minValue ( ((list int) lst) )
	(minValHelper lst 0)	
)

;;;Question 4
(define int avgValueHelper (((list int) lst) (int c) (int sum))
	(if (nullI lst)
		(/ sum c)
		(avgValueHelper (cdrI lst) (+ c 1) (+ sum (carI lst)))
	)
)
(define int avgValue (((list int)lst))
	(if (nullI lst)
		0
		(avgValueHelper lst 0 0)
	)
)
;;;Question 5
(define int lengthI (((list int) lst))
	(if (nullI lst)
		0
		(+ 1 (lengthI (cdrI lst)))
	)
)
(define (list int) appendI (((list int) lst1) ((list int) lst2))
	(if (nullI lst1)
		lst2
		(appendI (cdrI lst1) (consI (carI lst1) lst2))
	)
)
(define (list int) removeVal ( ((list int) lst) (int x) ((list int) ret) )
	(if (eqI x (carI lst))
		(appendI (cdrI lst) ret)
		(removeVal (cdrI lst) x (consI (carI lst) ret))
	)
)
(define int medValHelper ( ((list int) lst) (int len) )
	(if (eqI len 0)
		(minValue lst)
		(medValHelper  (removeVal lst (minValue lst) empty-int ) (- len 1))
	)
)
(define int mod ( (int val) (int div) )
	(if (< val div)
		val
		(mod (- val div) div)
	)
)
(define int medValue (((list int) lst))
	(if (nullI lst)
		0
		(if (eqI (mod (lengthI lst) 2) 0)
			(/ (+ (medValHelper lst (/ (- (lengthI lst) 1)  2))  (medValHelper lst (/ (lengthI lst) 2))) 2)
 			(medValHelper lst (/ (lengthI lst)  2))  
		)	
	)
)

;;question 1 tests
;(findInList '(1 2 3 4) 3)
;(findInList '(1 2 3 4) 5)
;(findInList empty-int 5)
;;;;Question 2 tests
;(maxValue '(1 2 3 4) )
;(maxValue empty-int )
;(maxValue '(5 2 4 6 9 7 18) )
;(maxValue '(25 2 4 6 9 7 18) )
;(maxValue '(25 2 4 66 9 7 18) )
;;Question 3 tests
;(minValue '(1 2 3 4) )
;(minValue empty-int )
;(minValue '(5 2 4 6 9 7 1) )
;(minValue '(5 4 9 7 18) )
;(minValue '(5 4  9 7 18) )
;;;Question 4 tests
;;;'()
;(avgValue  '(1 2 3 4 5) )
;(avgValue  '(11 22 33 44 55) )
;(avgValue  '(11 22 33 44) )
;(avgValue  empty-int )
;(avgValue  '(5) )
;;;Question 5 tests
;(medValue  '(1 2 3 4) )
;(medValue  '(1 2 3 4 5) )
;(medValue  '(5 23 4 1 2) )
;(mod 5 2)
;(mod 4 2)
;(use prog05_test.scm)
;(medValue '(100 101 65 76 32 86))
